<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mc_cookie"
 *
 * Auto generated by Extension Builder 2021-03-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'mc_2click_youtube_google',
    'description' => 'Extension to install a DSGVO / GDPR compliant 2-click-solution for Google Map Iframes and YouTube Iframes in a TYPO3 installation. ',
    'category' => 'templates',
    'author' => 'Rafael Gonzalez Albes',
    'author_email' => 'albes@mediaconcept-ulm.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
